// Renders docs/GATE.md's measured table from the recorded gate smoke runs (never hand-typed).
//   node scripts/gate-summary.ts runs/gate-smoke-2026-09-28
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
const dir = process.argv[2] ?? 'runs/gate-smoke-2026-09-28';
const nr = (xs: number[], q: number) => { if (!xs.length) return null; const s = [...xs].sort((a, b) => a - b); return s[Math.max(0, Math.ceil(q * s.length) - 1)]; };
const L = [`<!-- generated by scripts/gate-summary.ts from ${dir}; do not edit by hand -->`,
  '| recorded run | shadow judge in the app | other load on the GPU | hard-rule preflights (ms, max) | judged preflights p50 / p95 (ms) | allowed and executed | prevented (not executed under deny or hold) | allowed but not executed |', '|---|---|---|---|---|---|---|---|'];
for (const f of readdirSync(dir).filter(f => f.endsWith('.json')).sort()) {
  const r = JSON.parse(readFileSync(join(dir, f), 'utf8')) as { config: { shadow_judge: string; extra_load?: string }; gate_metrics: { prevented: number; executed_under_allow: number; not_executed_under_allow: number };
    controls: Array<{ decided_by: string; sdk_preflight_ms: number | null }> };
  const rule = r.controls.filter(c => c.decided_by === 'rule').map(c => c.sdk_preflight_ms).filter((v): v is number => v != null);
  const judged = r.controls.filter(c => c.decided_by !== 'rule').map(c => c.sdk_preflight_ms).filter((v): v is number => v != null);
  L.push(`| \`${f.replace('.json', '')}\` | ${r.config.shadow_judge} | ${r.config.extra_load ?? 'none'} | ${rule.length ? Math.max(...rule) : '—'} | ${nr(judged, 0.5) ?? '—'} / ${nr(judged, 0.95) ?? '—'} (n=${judged.length}) | ${r.gate_metrics.executed_under_allow} | ${r.gate_metrics.prevented} | ${r.gate_metrics.not_executed_under_allow} |`);
}
L.push('<!-- /generated -->');
console.log(L.join('\n'));
